export interface BalanceCheckpointRecord {
  balance: unknown;
  currency: string;
  as_of_date: string;
  created_at: string;
  calculated_balance_before: unknown | null;
  reconciliation_delta: unknown | null;
  calculation_start_date: string | null;
  calculation_basis: "monthly_net" | "tracked_balance" | null;
}

export interface BalanceMovement {
  amount: unknown;
  currency: string;
  date: string;
  created_at: string;
}

export interface BalanceCurrencyTotal {
  currency: string;
  amount: number;
}

export interface BalanceMovementTotals {
  incomes: BalanceCurrencyTotal[];
  expenses: BalanceCurrencyTotal[];
  investmentTransfers: BalanceCurrencyTotal[];
}

/**
 * A checkpoint already includes movements posted before it. A movement affects
 * the tracked balance only when it is dated later, or was entered later on the
 * same calendar date. `created_at` must therefore be generated by the server.
 */
export function isMovementAfterCheckpoint(
  movement: BalanceMovement,
  checkpoint: Pick<BalanceCheckpointRecord, "as_of_date" | "created_at">
) {
  if (movement.date > checkpoint.as_of_date) return true;
  if (movement.date < checkpoint.as_of_date) return false;

  return (
    Date.parse(movement.created_at) > Date.parse(checkpoint.created_at)
  );
}

/** Aggregate two-decimal ledger rows as integer cents to avoid float drift. */
export function aggregateBalanceMovements(
  movements: BalanceMovement[]
): BalanceCurrencyTotal[] {
  const centsByCurrency = new Map<string, number>();

  for (const movement of movements) {
    const amount = Number(movement.amount);
    if (!Number.isFinite(amount)) continue;
    const currency = movement.currency.toUpperCase();
    const cents = Math.round(amount * 100);
    centsByCurrency.set(
      currency,
      (centsByCurrency.get(currency) ?? 0) + cents
    );
  }

  return Array.from(centsByCurrency.entries())
    .map(([currency, cents]) => ({ currency, amount: cents / 100 }))
    .sort((left, right) => left.currency.localeCompare(right.currency));
}

export function calculateTrackedBalance({
  checkpoint,
  totals,
  convert,
}: {
  checkpoint: BalanceCheckpointRecord | null;
  totals: BalanceMovementTotals;
  convert: (amount: number, currency: string) => number;
}): number | null {
  if (!checkpoint) return null;

  const sumConverted = (rows: BalanceCurrencyTotal[]) =>
    rows.reduce(
      (sum, row) => sum + convert(Number(row.amount), row.currency),
      0
    );

  return (
    convert(Number(checkpoint.balance), checkpoint.currency) +
    sumConverted(totals.incomes) -
    sumConverted(totals.expenses) -
    sumConverted(totals.investmentTransfers)
  );
}
