#!/usr/bin/env python3
"""Generate seed SQL for public.categorization_rules from the rule tables in
generate_santander_import.py (BANK_CATEGORY_MAP + PATTERN_RULES).

Importing the maps directly (instead of copying them) guarantees the seed can
never drift from the Python import path.

Usage:
    python3 scripts/generate_categorization_rules_seed.py \
        > supabase/migrations/2026-07-03-seed-categorization-rules.sql

The output is idempotent (ON CONFLICT DO NOTHING) and resolves the single
app user and category ids by name at execution time, mirroring how the
import script resolves them.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from generate_santander_import import BANK_CATEGORY_MAP, PATTERN_RULES  # noqa: E402


def sql_string(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def main() -> None:
    rows: list[tuple[str, str, str, int]] = []  # (match_type, pattern, category_name, priority)

    # Merchant keyword patterns run FIRST in classify_expense → lower priority
    # number = evaluated earlier. Preserve list order.
    priority = 10
    for category_name, patterns in PATTERN_RULES:
        for pattern in patterns:
            rows.append(("merchant_keyword", pattern, category_name, priority))
        priority += 10

    # Bank-category fallbacks run AFTER keywords → high priority numbers.
    for bank_category, category_name in sorted(BANK_CATEGORY_MAP.items()):
        rows.append(("bank_category", bank_category, category_name, 1000))

    lines = [
        "-- ============================================",
        "-- Seed categorization_rules from scripts/generate_santander_import.py",
        "-- Generated by scripts/generate_categorization_rules_seed.py — do not edit by hand.",
        "-- Idempotent: safe to re-run. Apply wherever categorization_rules lives.",
        "-- ============================================",
        "",
        "DO $$",
        "DECLARE",
        "    ctx_user_id UUID;",
        "BEGIN",
        "    SELECT id INTO STRICT ctx_user_id FROM auth.users LIMIT 1;",
        "",
        "    INSERT INTO public.categorization_rules",
        "        (user_id, match_type, pattern, category_id, priority, source)",
        "    SELECT ctx_user_id, seed.match_type, seed.pattern, cat.id, seed.priority, 'seed'",
        "    FROM (VALUES",
    ]

    value_lines = [
        f"        ({sql_string(match_type)}, {sql_string(pattern)}, {sql_string(category)}, {priority})"
        for match_type, pattern, category, priority in rows
    ]
    lines.append(",\n".join(value_lines))

    lines += [
        "    ) AS seed(match_type, pattern, category_name, priority)",
        "    JOIN public.categories AS cat",
        "      ON lower(cat.name) = lower(seed.category_name)",
        "     AND (cat.user_id = ctx_user_id OR cat.user_id IS NULL)",
        "    ON CONFLICT (user_id, match_type, pattern) DO NOTHING;",
        "END $$;",
        "",
    ]

    sys.stdout.write("\n".join(lines))


if __name__ == "__main__":
    main()
